### ISSUE TITLE
tried this on popos, it's great

### ISSUE THREAD

**Issue by BarbzYHOOL** [keshavbhatt/ultimate-media-download-linux#3]
Hey, I tried this without expecting much but it's great and easy to use
I didn't know there were paid apps on POPOS software center though so since I don't have money, I can't afford it but just wanted to say it seems like a great app

also there was a typo "btach" instead of "batch" i guess

**Comment by keshavbhatt** [comment]
Thank you for checking it out:)
You can continue to use the application's basic functions. The premium edition only adds a few more advanced options and settings. I had to opt to have the paid version of application so that it can sustain longer and motivate me to work on it.
Also thanks for noticing the typo, i will provide a fix soon.

**Comment by BarbzYHOOL** [comment]
Oh cool, the only other good similar program is jdwonloader (i tried all the others available) but when i tried yours, i felt like it was easier to use!
I'm gonna use yours then. Maybe explain a little more in the app about the free version and the premium version?

And yes, I was very perplex as to why it worked that well for a new program made by one person, I tried to download on arte.tv and youtube and it worked flawlessly, then i thought "oh maybe because it is a premium software, it is why it works well".
Anyway, just wanted to give a shout out, I always support the underdogs :P
